---
Name: sunnysvgimages
After:
  - 'framework/*'
---
SilverStripe\Admin\LeftAndMain:
  extra_requirements_css:
    - 'sunnysideup/silverstripe-svg-images:css/svg-images.css'

SilverStripe\Assets\File:
  app_categories:
    image:
      - svg
  class_for_file_extension:
    svg: Sunnysideup\SilverStripeSvg\SVGImage

# Optionally uncomment this to have has_one images loaded as SVG in case of .svg extension
# You would also need to hack the core framework's ForeignKey class for this to work, see README
#Injector:
#  Image:
#    class: SVGImage
